# Pipeline de testes para aplicação Java usando GitHub Actions e Maven
# Este arquivo configura um workflow que:
# - Executa em pushes e pull requests na branch 'main'
# - Configura o ambiente com Java 11
# - Usa Maven para rodar os testes unitários

name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Configuração de cache para o Maven
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Executar os testes
    - name: Run Maven clean build and tests
      run: mvn clean verify
